### PR TITLE
add 3 models

### PR DESCRIPTION
**Pull request by dereyly**
1x5_all -- in model "5x5_to_3x3_to_1x3_AND_faster_lr_AND_PReLU"  replace all 1x3 to 1x5. Complex same as 3x3+1x1

1x3_sz_augm -- model "5x5_to_3x3_to_1x3_AND_faster_lr_AND_PReLU" data layer use size augmentation. There are a few changes in caffe-elu. 

darknet_bn -- model darknet from fast YOLO https://github.com/pjreddie/darknet/blob/master/cfg/darknet.cfg. Extend LSUV init, PreLU and BN

### CODE REVIEW

**Comment by ducha-aiki** [comment]
Thanks :)

1x3_sz_augm starts only from 60K iterations...Is the start available for it?

**Comment by dereyly** [comment]
before 60k iteations i have failed logs with test data. I use standard dataset for test without scaling 0.04 and have 0% accuracy

**Comment by ducha-aiki** [comment]
OK

**Comment by ducha-aiki** [comment]
DarkNet is interesting. Thanks!

**Pull request merged**
